version: '3.8'

services:
  app:
    build: .
    container_name: nestJS-starter
    restart: unless-stopped
    env_file: .env
    ports:
      - '3000:3000'
    volumes:
      - ./media/uploads:/app/uploads
      - ./media/uploads/images:/app/uploads/images
      - ./media/uploads/thumbnails:/app/uploads/thumbnails
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: ""
      ME_CONFIG_MONGODB_ADMINPASSWORD: ""
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - mongo

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    restart: unless-stopped
    ports:
      - '8002:8001'
    volumes:
      - redisinsight_data:/db

volumes:
  mongo_data:
  redis_data:
  redisinsight_data: